name: '发送邮件'
on:
#  push:
#  schedule:
#    - cron: '0 21 * * *'
  watch:
    types: started
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download Mail'
        run: wget --no-check-certificate -O mail.html ${{ secrets.MAIL_DL_URL }}
      - name: 'Send Mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ secrets.MAIL_SUBJECT }}
          body: file://mail.html
#          body: ${{ secrets.MAIL_BODY }}
          to: ${{ secrets.MAIL_TO }}
          from:  ${{ secrets.MAIL_FROM }}
          content_type: text/html
