name: '发送邮件'
on:
#  push:
#  schedule:
#    - cron: '0 21 * * *'
  watch:
    types: started
jobs:
  Send Email:
    runs-on: ubuntu-latest
    steps:
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ secrets.MAIL_SUBJECT }}
          body: file://result.html
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions
          content_type: text/html
